services:
  - type: web
    name: yeelight
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: YEELIGHT_IP
        value: 192.168.1.26  # Cambia esto por la IP de tu tira LED 